services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: dubimin
      MYSQL_DATABASE: sample_db
    volumes:
      - dbdata:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASS: dubimin
      DB_NAME: sample_db
      PORT: "8080"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  dbdata: {}
